config/routes.rb
Rails.application.routes.draw do

  root to: 'communities#index'
  devise_for :members

  resources :communities, only: [:show, :index, :new, :create] do
    resources :restaurants, only: [:create]
    resources :groups, only: [:index, :create, :update]
  end
  resources :restaurants, only: [:show, :destroy]
  resources :groups, only: [:destroy]
  resources :members, except: [:index]
  resources :reviews, only: [:create, :edit, :update, :destroy]

  post "/members/:id/join_community/:community_id", to: "members#join_community", as: "member_join_community"
  post "/members/:id/leave_community/:community_id", to: "members#leave_community", as: "member_leave_community"

  get "/members/:id/join_group/:group_id", to: "members#join_group_from_email", as: "member_join_group_from_email"
  post "/members/:id/join_group/:group_id", to: "members#join_group", as: "member_join_group"
  post "/members/:id/leave_group", to: "members#leave_group", as: "member_leave_group"

  get "yelp_call", to: "restaurants#yelp_call"
end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :community
  belongs_to :restaurant
  has_many :members
  belongs_to :creator, :class_name => "Member"

  validates_presence_of :community, :restaurant, :time

  def show_time
    time.strftime("%l:%M")
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :get_community, :authenticate_member!, :authenticate_member_of_community

  def index
    @groups = @community.groups
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      current_member.group = @group
      current_member.save
      #For some reason select2 always submits one empty string at the beginning of the array.
      #Saw some possible fixes online, but did not work
      #Will keep trying to figure this out
      mailer = InvitationMailer.new(params["invitee_ids"][1..-1], @group) if params["invitee_ids"].length > 1
      mailer.send_invitations
      #Need to find a way to get flash messages to display on AJAX response
      #flash[:notice] = "Group successfully created."
    else
      #flash[:alert] = "Error: Group must have a name and a time."
    end
  end

  def update
    @group = Group.find(params[:id])
    @group.update(group_params)
  end

  def destroy
    @group = Group.find(params[:id])
  end

  private

    def get_community
      @community = Community.find(params[:community_id])
    end

    def group_params
      params.require(:group).permit(:time, :info, :restaurant_id, :community_id, :creator_id)
    end

    def authenticate_member_of_community
      unless @community.members.include?(current_member)
        flash[:alert] = "You must be a member of this community to see its lunch groups!"
        redirect_to communities_path
      end
    end

end

app/views/groups/_form.html.erb
<div id="new-group" class="row">
  <div class="col-sm-6">
    <h3>Create a new group:</h3>
    <%= form_for [community, Group.new], remote: true, html: {class: "form-horizontal"} do |f| %>

      <%= f.hidden_field :community_id, value: community.id %>
      <%= f.hidden_field :creator_id, value: current_member.id %>

      <div class="row">
        <div class="form-group col-sm-8">
          <%= f.collection_select :restaurant_id, community.restaurants, :id, :name,
              {prompt: "Choose a Local Restaurant"}, {class: "form-control"} %>
        </div>
      </div>

      <div class="row">
        <div class="form-group col-sm-3">
          <%= f.text_field :time, class: "form-control", placeholder: "Time" %>
        </div>
      </div>

      <div class="row">
        <div class="form-group col-sm-6">
          <%= f.text_area :info, class: "form-control", placeholder: "Extra Information" %>
        </div>
      </div>

      <div class="row">
        <div class="form-group col-sm-6">
          <label for="_invitee_ids">Invite Friends!</label>
          <%= collection_select(nil, :invitee_ids, other_members_of_community(community), :id, :name, {include_blank: true}, {class: "form-control", multiple: true}) %>
        </div>
      </div>

      <div class="form-group">
        <%= f.submit "Submit", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>

  <script type="text/javascript">

  $(function(){
    $('#_invitee_ids').select2();
  });

  function setTimePicker($timeField, startTime){
    var $timepicker = $timeField,
        inFiveHours = new Date();
    inFiveHours.setHours(new Date().getHours() + 5);
    $timepicker.timepicker({
      'scrollDefault': 'now',
      'minTime': new Date(),
      'maxTime': inFiveHours,
      'step': 15
    });
    $timepicker.timepicker('setTime', startTime);
    $timepicker.on('changeTime', function() {
      console.log('change');
      console.log($(this).val());
    });
  };

    // Setting up Date object set to 20 minutes from now for new group form
    inTwentyMinutes = new Date();
    inTwentyMinutes.setMinutes(new Date().getMinutes() + 20);
    setTimePicker($('#new_group input[name="group[time]"]'), inTwentyMinutes);

    //Setting up timepicker for hidden forms to change restaurant times
    $(".current-member-group").each(function(index, group){
      var groupTime = $(this).find(".group-time").text().trim();
      var timeChangeForm = $(group).find('input[name="group[time]"]');
      var groupHour = groupTime.split(":")[0];
      var groupMinutes = groupTime.split(":")[1];
      if(groupHour.length == 1){
        console.log(groupHour);
        groupTime = groupHour + ":" + groupMinutes + "pm";
      };
      setTimePicker(timeChangeForm, groupTime);
    });

  </script>
</div>

app/views/groups/_group.html.erb
<!-- <div id="group-<%#= group.id %>" class="group<%#= " current-member-group" if group.creator == current_member %> col-sm-4"> -->  <!-- Not fully implemented -->
<div id="group-<%= group.id %>" class="group col-sm-4">
  <h2 class="group-restaurant"><%= group.restaurant.name %>,</h2>
  <h3 class="group-time"><%= group.show_time %></h3>

  <!-- Not fully implemented -->
  <%# if group.creator == current_member %>
    <!-- <div class="update-time"> -->
      <%#= form_for [community, group], remote: true, html: {class: "form-horizontal"} do |f| %>
        <%#= f.hidden_field :community_id, value: community.id %>
        <!-- <div class="form-group col-sm-3"> -->
          <%#= f.text_field :time, class: "form-control", placeholder: "Time" %>
        <!-- </div> -->
      <%# end %>
    <!-- </div> -->
  <%# end %>

  <h4 class="group-info"><%= group.info %></h4>
  <div class="group-members">
    <h4>Lunchers:</h4>
    <% if group.members.empty? %>
      <h5>Nobody! :(</h5>
    <% else %>
      <ul class="list-unstyled">
      <% group.members.each do |member| %>
        <li><h5><%= member.name %></h5></li>
      <% end %>
      </ul>
    <% end %>
    <div class="group-join-leave">
      <% if current_member.group == group %>
        <%= button_to "Leave Group", member_leave_group_path(current_member), remote: true, class: "leave-group btn btn-xs btn-danger" %>
      <% else %>
        <%= button_to "Join Group", member_join_group_path(current_member, group), remote: true, class: "join-group btn btn-xs btn-success" %>
      <% end %>
    </div>
  </div>
</div>

<!-- Not fully implemented -->
<script type="text/javascript">
//   $(function(){
//     $(".update-time").hide();
//   })
</script>

app/views/groups/create.js.erb
$('#groups').append('<%= j render partial: "groups/group", locals: {group: @group, community: @group.community} %>');

app/views/groups/index.html.erb
<h1><%= @community.name %> Lunch Groups</h1>

<div id="groups" class="row">
  <%= render partial: "group", collection: @groups, locals: {community: @community} %>
</div>

<%= render 'form', community: @community, mailer: @mailer %>

<%# TODO: There should be the ability to create a restaurant from here!! %>

app/views/groups/update.js.erb
$groupTime = $("#group-<%= @group.id %>").find(".group-time")
$groupTime.html("<%= @group.show_time %>")
$groupTime.show();
$groupTime.closest(".group").find(".update-time").hide();