config/routes.rb
Rails.application.routes.draw do

  root to: 'communities#index'
  devise_for :members

  resources :communities, only: [:show, :index, :new, :create] do
    resources :restaurants, only: [:create]
    resources :groups, only: [:index, :create, :update]
  end
  resources :restaurants, only: [:show, :destroy]
  resources :groups, only: [:destroy]
  resources :members, except: [:index]
  resources :reviews, only: [:create, :edit, :update, :destroy]

  post "/members/:id/join_community/:community_id", to: "members#join_community", as: "member_join_community"
  post "/members/:id/leave_community/:community_id", to: "members#leave_community", as: "member_leave_community"

  get "/members/:id/join_group/:group_id", to: "members#join_group_from_email", as: "member_join_group_from_email"
  post "/members/:id/join_group/:group_id", to: "members#join_group", as: "member_join_group"
  post "/members/:id/leave_group", to: "members#leave_group", as: "member_leave_group"

  get "yelp_call", to: "restaurants#yelp_call"
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :get_review, only: [:edit, :update, :destroy]

  before_action :authenticate_member!

  def create
    @review = Review.create(review_params)
    @review.member = current_member
    render :create_errors if !@review.save
  end

  def edit
  end

  def update
    @review.update(review_params)
    render :update_errors if !@review.save
  end

  def destroy
    @review.destroy
  end

  private

    def get_review
      @review = Review.find(params[:id])
    end

    def review_params
      params.require(:review).permit(:text, :rating, :restaurant_id)
    end

end

app/views/reviews/_edit.html.erb
<div class="review-form">
  <h3>Edit Review</h3>
  <%= render "reviews/form", review: review, submit_text: "Update" %>
</div>

app/views/reviews/_form.html.erb
<%= form_for(review, html: {class: "form-horizontal"}, remote: true) do |f| %>

  <%= render 'shared/errors', object: review %>

  <%= f.hidden_field :restaurant_id %>

  <div class="form-group">
    <%= f.label :stars, class: "form-label col-sm-1" %>
    <div class="col-sm-2">
    <div id="star-rating-<%= review.persisted? ? review.id : "new" %>"></div>
    <%= f.hidden_field :rating, id: "review-rating-#{review.persisted? ? review.id : 'new'}" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :text, "Body", class: "form-label col-sm-1" %>
    <div class="col-sm-6">
      <%= f.text_area :text, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-4 col-sm-offset-1 cancel-submit-buttons">
      <%= f.button submit_text, type: 'submit', class: "btn btn-primary" %>
      <%= f.button "Cancel", id: "#{review.id}-cancel", class: "btn btn-danger" %>
    </div>
  </div>

  <script type="text/javascript">
    var $starRating = $('#star-rating-<%= review.persisted? ? review.id : "new" %>'),
        $reviewRating = $('#review-rating-<%= review.persisted? ? review.id : "new" %>');
    $starRating.raty({
      click: function(score, evt) {
        var rating = score;
        $reviewRating.val(rating);
      }
    });
    <% if review.persisted? %>
      $starRating.raty('click', <%= review.rating %>);
    <% end %>
  </script>

<% end %>

app/views/reviews/_new.html.erb
<div class="review_form">
  <h3>New Review</h3>
  <%= render "reviews/form", review: review, submit_text: "Submit" %>
</div>

app/views/reviews/_review.html.erb
<div id="review-<%= review.id %>" class="row">
  <div class="col-sm-10">
    <h4>
      <strong><%= "#{review.rating} -" %></strong>
      <%= link_to review.member.name, member_path(review.member) %>

    </h4>
    <div class="review-text"><%= review.text %></div>
    <% if review.member == current_member %>
      <div class="review-edit-delete">
        <%= button_to "Edit", edit_review_path(review), method: :get, remote: true, class: 'btn btn-primary btn-sm' %>
        <%= button_to "Delete", review_path(review), method: :delete, remote: true, class: 'btn btn-danger btn-sm' %>
      </div>
    <% end %>
  </div>
</div>

app/views/reviews/create.js.erb
$('#reviews').append("<%= j render @review %>");
var $new_review = $('#new_review');
$new_review[0].reset();
$new_review.find('#star-rating-new').raty('score', 0);
$new_review.find('.error_explanation').remove();

app/views/reviews/create_errors.js.erb
var $new_review = $('#new_review');
$new_review.find('.error_explanation').remove();
$new_review.prepend("<%= j render 'shared/errors', object: @review %>");

app/views/reviews/destroy.js.erb
var $review = $('#review-' + <%= @review.id %>);
$review.remove();

app/views/reviews/edit.js.erb
var $review = $('#review-' + <%= @review.id %>);
$review.children().hide();
$review.hide();
$review.append("<%= j render 'reviews/edit', review: @review %>");
$review.slideDown();

app/views/reviews/errors.js.erb
var $new_review = $('#new_review');
$new_review.find('#error_explanation').remove();
$new_review.prepend("<%= j render 'shared/errors', object: @review %>");

app/views/reviews/update.js.erb
var $review = $('#review-' + <%= @review.id %>);
$review.replaceWith("<%= j render @review %>");

app/views/reviews/update_errors.js.erb
var $review_form = $('#review-' + <%= @review.id %> + ' form');
$review_form.find('#error_explanation').remove();
$review_form.prepend("<%= j render 'shared/errors', object: @review %>");