config/routes.rb
Rails.application.routes.draw do

  root to: 'communities#index'
  devise_for :members

  resources :communities, only: [:show, :index, :new, :create] do
    resources :restaurants, only: [:create]
    resources :groups, only: [:index, :create, :update]
  end
  resources :restaurants, only: [:show, :destroy]
  resources :groups, only: [:destroy]
  resources :members, except: [:index]
  resources :reviews, only: [:create, :edit, :update, :destroy]

  post "/members/:id/join_community/:community_id", to: "members#join_community", as: "member_join_community"
  post "/members/:id/leave_community/:community_id", to: "members#leave_community", as: "member_leave_community"

  get "/members/:id/join_group/:group_id", to: "members#join_group_from_email", as: "member_join_group_from_email"
  post "/members/:id/join_group/:group_id", to: "members#join_group", as: "member_join_group"
  post "/members/:id/leave_group", to: "members#leave_group", as: "member_leave_group"

  get "yelp_call", to: "restaurants#yelp_call"
end

app/models/community.rb
class Community < ActiveRecord::Base
  has_many :restaurants
  has_many :groups
  has_many :member_communities
  has_many :members, through: :member_communities

  validates_presence_of :name
  validate :validate_latitude_and_longitude

  def existing_restaurant(yelp_url)
    restaurants.where(yelp_url: yelp_url).first
  end

  def address=(address)
    self.latitude, self.longitude = Geocoder.coordinates(address)

  end

  private

  def validate_latitude_and_longitude
    if self.latitude == nil || self.longitude == nil
      self.errors.add(:base, "Not a valid address")
    end
  end
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_action :authenticate_member!, except: [:index]
  before_action :get_community, only: [:show]
  before_action :authenticate_member_of_community, only: [:show]

  def index
    @communities = Community.all
  end

  def show
    @restaurants = Restaurant.by_average_rating_for_community(@community.id).paginate(:page => params[:page], :per_page => 8)
  end

  def new
    @community = Community.new
  end

  def create
    @community = Community.new(community_params)
    if @community.save
      flash[:notice] = "Community created succcessfully"
      redirect_to @community
    else
      render :new
    end
  end

  private

    def get_community
      @community = Community.find(params[:id])
    end

    def authenticate_member_of_community
      unless @community.members.include?(current_member)
        flash[:alert] = "You must be a member of this community to see it!"
        redirect_to communities_path
      end
    end

    def community_params
      params.require(:community).permit(:name, :address)
    end

end

app/views/communities/_community.html.erb
<div class="community">
  <div class="row">
    <div class="col-xs-12">
      <h1 class="name"><%= (member_signed_in? && current_member.communities.include?(community))  ? link_to(community.name, community) : community.name %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 members">
      <h4><%= pluralize community.members.count, "Member" %></h4>
      <% if member_signed_in? %>
        <% if current_member.communities.include?(community) %>
          <%= button_to 'Leave', member_leave_community_path(current_member, community), class: "btn btn-danger btn-sm", form: {class: "pull-right"} %>
        <% else %>
          <%= button_to 'Join', member_join_community_path(current_member, community), class: "btn btn-success btn-sm", form: {class: "pull-right"} %>
        <% end %>
      <% end %> <!-- end member_signed_in? -->
    </div>
  </div>
</div>

app/views/communities/_form.html.erb
<%= form_for(community, html: {class: "form-horizontal") do |f| %>

  <%= render 'shared/errors', object: community %>

  <div class="form-group">
    <%= f.label :name %>
    <div class="row">
      <div class="col-sm-4">
        <%= f.text_field :name, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :latitude %>
    <div class="row">
      <div class="col-sm-2">
        <%= f.text_field :latitude, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :longitude %>
    <div class="row">
      <div class="col-sm-2">
        <%= f.text_field :longitude, class: "form-control" %>
      </div>
    </div>
  </div>

  <%= f.button, 'Create', type: 'submit', class: "btn btn-primary" %>

<% end %>

app/views/communities/_page.html.erb
<% restaurants.each do |restaurant| %>
  <div id="restaurant-<%= restaurant.id %>" class="restaurant">
    <h3 class="name"><%= link_to restaurant.name, restaurant %></h3>
    <h5 class="category">(<%= restaurant.category %>)</h5>
    <h5 class="address"><%= restaurant.address %></h5>
  </div>
<% end %>
<%= will_paginate restaurants, params: {is_active: true} %>

app/views/communities/index.html.erb
<div class="row">
  <div id="about-wrapper" class="col-xs-12 col-sm-6 col-md-8">
    <div id="about">

      <h1 class="title">Lunchpad</h1>

      <p class="lead">
        The internet is full of opinions on where you should eat, but can you trust the source?
      </p>
      <p class="lead">
        Local Lunch provides you with restaurant recommendations written by the people in your office.
      </p>
      <p class="lead">
        Caballero's might be great in general, but Jim in Accounting will know that it's not a good option for your team since there is no way to make it through their line during your measly 20 minute lunch break. It's this kind of inside info that makes lunch a great success.
      </p>
      <p class="lead">
        Once you've selected the perfect restaurant, make it even better by going with friends! Local Lunch makes it easy to form a lunch group so other people can join you on your culinary adventure.
      </p>
    </div>
  </div>

  <div id="communities-list" class="row col-xs-12 col-sm-6 col-md-4">
    <h2>Open Communities</h2>
    <% if member_signed_in? %>
    <%= render current_member.communities %>
    <%= render current_member.foreign_communities %>
    <% else %>
    <%= render @communities %>
    <% end %>
  </div>

  <% if member_signed_in? %>
    <%= button_to 'Create a New Community', new_community_path, method: :get, id: "new-community-button", class: "btn btn-lg btn-success" %>
  <% end %>
</div>

<%= content_for :footer do %>
  <div id="footer" class="row">
    <div class="col-xs-12">
      <p class="lead">
        Lunchpad was made at The Flatiron School by
        <%= link_to "Brandon", "https://github.com/bajh" %> (<%= link_to "@bhkns", "https://twitter.com/bhkns"%>),
        <%= link_to "Peter", "https://github.com/pcrglennon" %> (<%= link_to "@pcrglennon", "https://twitter.com/pcrglennon"%>),
        <%= link_to "Jessica", "https://github.com/jessrudder" %> (<%= link_to "@jessrudder", "https://twitter.com/jessrudder"%>),
        <%= link_to "Simon", "https://github.com/simonseroussi" %> (<%= link_to "@simonseroussi", "https://twitter.com/simonseroussi"%>).  We take our lunchtime shenanigans seriously.
      </p>
    </div>
  </div>
<% end %>

app/views/communities/new.html.erb
<h1>New Community</h1>

<%= form_for(@community, html: {class: "form-horizontal"}) do |f| %>

  <%= render 'shared/errors', object: @community %>

  <div class="form-group">
    <%= f.label :name, "Name:", class: "col-sm-2 control-label" %>
    <div class="col-sm-6">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <label for="community_address" class="col-sm-2 control-label">Address: </label>
    <div class="col-sm-6">
      <input type="text" id="community_address" name="community[address]" class="form-control">
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-10 col-sm-offset-2">
      <%= f.button 'Create', type: 'submit', class: "btn btn-primary" %>
    </div>
  </div>

<% end %>

app/views/communities/show.html.erb
<div id="community-header" class="row">
  <h1 class="name"><%= @community.name %></h1>
</div>

<div class="row">
  <div class="col-sm-7">
    <div id="restaurant-list">
      <%= render 'page', restaurants: @restaurants %>
    </div>
    <%= render 'restaurants/form', restaurant: Restaurant.new(community_id: @community.id) %>
  </div>

  <div id="community-map" class="col-sm-5">
    <div id="map-canvas"></div>
  </div>
</div>

<div class="row">
  <div class="col-sm-7">
  </div>
</div>

<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAiSQuuu6i2KkJvB9cBwnyW9oV4cXNvkmI">
</script>
<script type="text/javascript">
  var community = {
    latitude: <%= @community.latitude %>,
    longitude: <%= @community.longitude %>,
    name: '<%= @community.name %>'
  };

  var restaurants = [];
  <% @community.restaurants.each do |restaurant| %>
    var current_restaurant = [<%= restaurant.latitude %>, <%= restaurant.longitude %>, '<%= restaurant.name %>', <%= restaurant.id %>, '<%= restaurant.address %>', '<%= restaurant.yelp_url %>'];
    restaurants.push(current_restaurant);
  <% end %>
  loadCommMap(community, restaurants);

  $(document).ready(function(){
    $("#restaurant-list").on("click", ".pagination a", function(e){
      e.preventDefault();
      $.getScript(this.href);
      return false;
    })
  })

</script>

app/views/communities/show.js.erb
$("#restaurant-list").html("<%= escape_javascript(render("page", restaurants: @restaurants)) %>");