config/routes.rb
Rails.application.routes.draw do

  root to: 'communities#index'
  devise_for :members

  resources :communities, only: [:show, :index, :new, :create] do
    resources :restaurants, only: [:create]
    resources :groups, only: [:index, :create, :update]
  end
  resources :restaurants, only: [:show, :destroy]
  resources :groups, only: [:destroy]
  resources :members, except: [:index]
  resources :reviews, only: [:create, :edit, :update, :destroy]

  post "/members/:id/join_community/:community_id", to: "members#join_community", as: "member_join_community"
  post "/members/:id/leave_community/:community_id", to: "members#leave_community", as: "member_leave_community"

  get "/members/:id/join_group/:group_id", to: "members#join_group_from_email", as: "member_join_group_from_email"
  post "/members/:id/join_group/:group_id", to: "members#join_group", as: "member_join_group"
  post "/members/:id/leave_group", to: "members#leave_group", as: "member_leave_group"

  get "yelp_call", to: "restaurants#yelp_call"
end

app/views/layouts/_header.html.erb
<div class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-inverse-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "", root_path, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <% if member_signed_in? %>
          <% if current_member.communities.empty? %>
            <li><%= link_to "Join A Community!", communities_path %></li>
          <% else %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">My Communities<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <% current_member.communities.each do |community| %>
                  <li><%= link_to community.name, community %></li>
                  <li class="lunch-groups"><%= link_to " - Lunch Groups", community_groups_path(community) %></li>
                <% end %>
              </ul>
            </li>
          <% end %>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <% if member_signed_in? %>
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <%= current_member.email %><b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "My Profile", current_member %></li>
            <li><%= link_to "Profile Edit", edit_member_registration_path %></li>
            <li><%= link_to "Sign Out", destroy_member_session_path, method: :delete %></li>
          </ul>
          <% else %>
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Sign In/Sign Up <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Sign In", new_member_session_path %></li>
            <li><%= link_to "Sign Up", new_member_registration_path %></li>
          </ul>
          <% end %>
        </li>
      </ul>
    <!-- <form class="navbar-form navbar-left">
      <input type="text" class="form-control col-lg-8" placeholder="Search For A Community">
    </form> -->
  </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lunchpad</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= analytics_init if Rails.env.production? %>
</head>
  <body>

    <%= render 'layouts/header' %>

    <div class="container">

      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>

      <%= yield %>

    </div>

    <%= yield :footer %>
  </body>
</html>